/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Citoyen (void);
GtkWidget* create_Administrateur (void);
GtkWidget* create_Login (void);
GtkWidget* create_enregistrer (void);
GtkWidget* create_Moto (void);
GtkWidget* create_RS (void);
GtkWidget* create_Tun (void);
GtkWidget* create_mdp_oublie (void);
